---

url: "https://vectorhack.com"
name: VectorHack
description: "Machine learning news and insights"

timezone: Etc/GMT

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10

theme: jekyll-theme-minimal
