---

url: "https://vectorhack.com"
name: VectorHack
title: VectorHack
description: "Machine learning news and insights"

timezone: Etc/GMT

plugins:
  - jekyll-feed
  - jemoji

theme: jekyll-theme-minimal

google_analytics: UA-61345550-7
