---

url: "http://help.757live.co/"
name: VectorHack
title: VectorHack
description: "Machine learning news and insights"

timezone: Etc/GMT

plugins:
  - jekyll-feed
  - jemoji

theme: jekyll-theme-minimal

google_analytics: UA-613757-7
