---

url: "http://help.757live.co/"
name: 757Live Network
title: 757Live
description: "Machine learning news and insights"

timezone: Asia/Kolkata

plugins:
  - jekyll-feed
  - jemoji

theme: jekyll-theme-minimal

google_analytics: UA-613757-7
